name: GitHub Actions - Matrix strategy Template
run-name: Running - Matrix 
on: [push, workflow_dispatch]

jobs:
  matrix_job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        navegador: [chrome, firefox, webkit]
        tag: [tag_1, tag_2, tag_3]
      fail-fast: false
    steps:
      - name: Comments
        run: |
          echo ${{ matrix.navegador }}
          echo ${{ matrix.tag }}